from cstim.sounds.perExperiment.sequences.seq_class import Sequence
from cstim.sounds.perExperiment.sequences.patterns import ToneList,Local_Standard,Local_Deviant,RandomPattern
from cstim.sounds.perExperiment.sequences.patterns import FullCommunityGraph,SparseCommunityGraph
from cstim.sounds.perExperiment.sequences.lot_patterns import lot_patterns