from cstim.sounds.perExperiment.sound_elements.sound_class import Sound,Sound_pool
from cstim.sounds.perExperiment.sound_elements.sound_class import ramp_sound,normalize_sound,pitch_shift
from cstim.sounds.perExperiment.sound_elements.tones_elements import Bip,Bip_randPitch,gaussian_N,Silence
from cstim.sounds.perExperiment.sound_elements.speech_elements import FrenchSyllable,EnglishSyllable
from cstim.sounds.perExperiment.sound_elements.segment_elements import SoundSegment
